version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - postgres_adminer

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - postgres_adminer

  postgres:
    image: postgres:13.3
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    networks:
      - postgres_adminer
    volumes:
      - postgres:/data

  adminer:
    container_name: adminer_watcher
    hostname: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - postgres_adminer
  app:
    build:
      context: .
    container_name: test_task_books_dj
    command: [ "docker/app.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - adminer
      - kafka
    networks:
      - postgres_adminer

volumes:
  postgres:


networks:
  postgres_adminer:
    driver: bridge
