version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    networks:
      - postgres_adminer
    volumes:
      - postgres:/data

  adminer:
    container_name: adminer_watcher
    hostname: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - postgres_adminer
  app:
    build:
      context: .
    container_name: test_task_books_dj
    command: [ "docker/app.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - postgres_adminer

volumes:
  postgres:


networks:
  postgres_adminer:
    driver: bridge